version: 2

updates:
  - package-ecosystem: "cargo"
    directory: "cli"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "all"
    reviewers:
      - "DanHatesNumbers"
    commit-message:
      prefix: "Dependencies: "
      include: "scope"
  - package-ecosystem: "cargo"
    directory: "data-collector"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "all"
    reviewers:
      - "DanHatesNumbers"
    commit-message:
      prefix: "Dependencies: "
      include: "scope"
  - package-ecosystem: "cargo"
    directory: "data-forwarder"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "all"
    reviewers:
      - "DanHatesNumbers"
    commit-message:
      prefix: "Dependencies: "
      include: "scope"
  - package-ecosystem: "cargo"
    directory: "report-parser"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "all"
    reviewers:
      - "DanHatesNumbers"
    commit-message:
      prefix: "Dependencies: "
      include: "scope"
  - package-ecosystem: "cargo"
    directory: "slack-connector"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "all"
    reviewers:
      - "DanHatesNumbers"
    commit-message:
      prefix: "Dependencies: "
      include: "scope"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "all"
    reviewers:
      - "DanHatesNumbers"
    commit-message:
      prefix: "Dependencies: "
      include: "scope"
  - package-ecosystem: "docker"
    directory: "tool-images/ruby/bundler-audit"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "all"
    reviewers:
      - "DanHatesNumbers"
    commit-message:
      prefix: "Dependencies: "
      include: "scope"
  - package-ecosystem: "docker"
    directory: "tool-images/python/safety"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "all"
    reviewers:
      - "DanHatesNumbers"
    commit-message:
      prefix: "Dependencies: "
      include: "scope"
