site_name: 'Kiln'
site_description: 'Main documentation for Kiln'

plugins:
  - techdocs-core

nav:
  - Welcome: 'index.md'
  - Integration Testing: 'integration_testing.md'
  - Release Process: 'release-process.md'
