[package]
name = "data-forwarder"
version = "0.2.1"
edition = "2018"

[dependencies]
kiln_lib = { git = "https://github.com/simplybusiness/Kiln", rev = "d0f30c6beb4a8a9c60a72836ffb23131fcc48613", features = ["json", "toml"] }
clap = "2"  
chrono = "0.4"
reqwest = "0.9" 
git2 = "0.10"
uuid = { version = "0.8", features = ["v4"] }
openssl-probe = "0.1.2"
toml = "0.5"
retry = "1"
failure = "0.1"
