name: cargo audit
on:
    push:
        paths:
            - '**/Cargo.toml'
            - '**/Cargo.lock'
       
jobs:
    vulnerable-dependency-check:
        name: Check for dependencies on vulnerable crates
        runs-on: ubuntu-18.04
        steps:
            - uses: actions/checkout@v1
            - uses: actions-rs/toolchain@v1
              with:
                toolchain: stable
                  override: true
            - name: Install cargo audit
              runs: cargo install cargo-audit
            - name: Run cargo audit
              runs: cargo audit --deny-warnings 
              working-directory: /data-collector
