name: cargo audit
on:
    push:
        paths:
            - '**/Cargo.toml'
            - '**/Cargo.lock'
       
jobs:
    vulnerable-dependency-check:
        name: Check for dependencies on vulnerable crates
        runs-on: ubuntu-18.04
        steps:
            - name: Checkout
              uses: actions/checkout@v1
            - name: Audit
              uses: actions-rs/audit-check@v1
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
