name: Build release artifacts
on:
  push:
    branches:
      - release_automation

jobs:
  source-tarball:
    name: Archive source
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: 'src'
      - name: Import CI signing key
        run: echo -e "${{ secrets.AUTOMATED_SIGNING_PRIVATE_KEY }}" | gpg --import
      - name: Archive source
        run: tar -cJf kiln-source.tar.xz src/
      - name: Hash source archive
        run: sha256sum kiln-source.tar.xz > kiln-source.tar.xz.sha256
      - name: Sign hash file
        run: gpg --output kiln-source.tar.xz.sha256.sig --detach-sig kiln-source.tar.xz.sha256
      - name: Upload tarball
        uses: actions/upload-artifact@v1
        with:
          name: kiln-source.tar.xz
          path: kiln-source.tar.xz
      - name: Upload hash file
        uses: actions/upload-artifact@v1
        with:
          name: kiln-source.tar.xz.sha256
          path: kiln-source.tar.xz.sha256
      - name: Upload hash file signature
        uses: actions/upload-artifact@v1
        with:
          name: kiln-source.tar.xz.sha256.sig
          path: kiln-source.tar.xz.sha256.sig

  build-linux-packages:
    name: Build linux packages
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Import CI signing key
        run: echo -e "${{ secrets.AUTOMATED_SIGNING_PRIVATE_KEY }}" | gpg --import
      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          version: 2.6.x
      - name: Install fpm
        run: gem install --no-document fpm
      - name: Build CLI app
        run: cargo build --release && mkdir ../bin && cp target/release/kiln-cli ../bin/kiln
        working_directory: cli
      - name: Build .deb package
        run: fpm -s dir -t deb -C bin --name "kiln-cli" -v 0.2.0 --license MIT --vendor "Simply Business" -d "docker.io > 18.09" --provides "kiln" -m "kiln@simplybusiness.co.uk" --url "https://github.com/simplybusiness/Kiln" --deb-compression "xz" --deb-dist-tag "buster"
      - name: Upload .deb package
        uses: actions/upload-artifact@v1
        with:
          name: deb-package
          path: "*.deb"
